#########################Automated tests trace#########################

self = <MEGS.Tests.EdgeRole.test_edge_role.TestEdgeRole object at 0x035B98D0>

    def test_grant_edge_roles_to_single_system_user(self):
        test_roles_list = ["Test Custom Role {0}".format(datetime.now().strftime('%Y%m%d_%H%M%S'))]
        curr_roles_list = self._get_current_edge_role_list_by_system_user_id(self.es_client,self.test_user_id)["edgeRoles"]
    
        http_response = self.edge_role.grant_edge_role_to_single_user(self.test_user_id, test_roles_list)
        #check http response code
        assert http_response[0] in range(200, 299),\
            "Unable to grant edge role to single system user -{0}, system returns {1} error".format(
            self.test_user_id,
            http_response[0]
        )
    
        #check roles list in index
        self.assertSystemUserEdgeRolesInIndex(
            self.es_client,
            self.test_user_id,
>           test_roles_list + curr_roles_list
        )

C:\EdgeDeployment\FunctionalTests\src\MEGS\Tests\EdgeRole\test_edge_role.py:74: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <MEGS.Tests.EdgeRole.test_edge_role.TestEdgeRole object at 0x035B98D0>
es_client = <elasticsearch_client.elasticsearch_client object at 0x024F8470>
user_id = '913ced26-998d-e311-a5b4-00155d28de35'
curr_roles = ['Test Custom Role 20140218_025113', 'Test Custom Role 20140218_025107']

    def assertSystemUserEdgeRolesInIndex(self, es_client, user_id=None, curr_roles=None):
        edge_roles = self.get_edge_roles(es_client, user_id)
        if not edge_roles:
            edge_roles.append(self._get_system_user_business_unit(es_client, user_id))
        #check list edge roles in index equal to list of roles returned via REST API
>       assert set(curr_roles) == set(edge_roles)
E       assert set(['Test Cu...0218_025113']) == set(['Test Cus...0218_025113'])
E         Extra items in the left set:
E         'Test Custom Role 20140218_025107'

C:\EdgeDeployment\FunctionalTests\src\MEGS\Implementation\Assertions\EdgeRoleAssertMixin.py:13: AssertionError
-------------------------------- Captured log ---------------------------------
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_mapping HTTP/1.1" 200 443656
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/authentication
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'73bce4f4c9164851985add8927914419', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/authentication HTTP/1.1" 200 2124
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:01.907000
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 1425
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: PUT
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/EdgeRole/913ced26-998d-e311-a5b4-00155d28de35/
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'73bce4f4c9164851985add8927914419', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
requests_api.py            112 DEBUG    Request body: ["Test Custom Role 20140218_025113"]
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "PUT /xre2113qa.nightly/api/EdgeRole/913ced26-998d-e311-a5b4-00155d28de35/ HTTP/1.1" 200 21
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:01.283000
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 1426
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/systemuseredgeroles HTTP/1.1" 404 111
elasticsearch_client.py     60 WARNING  ValueWithVersion`1 entity has not been found in index xre2113qa.nightly.settings
connectionpool.py          296 DEBUG    "HEAD /xre2113qa.nightly/systemuseredgeroles/f532fcb9-dba5-4362-9948-c5cb4d5c3dd0 HTTP/1.1" 200 0
#########################Server error trace#########################
{"index":[],"megs":[]}
