#########################Automated tests trace#########################

self = <Tests.InitialPopulation.RelatedEntityCounts.test_aggregate_counts.TestAggregatedEntityCounts instance at 0x04011648>
entity_with_related_counts = <PyTest.InputTestCriteria.InputTestCriteria.EntityWithField object at 0x036A6510>
search_api = <Search.Implementation.Contract.search.SearchAPI object at 0x034776F0>

    @pytest.mark.xre_demo
    def test_related_entity_count(self, entity_with_related_counts, search_api):
        entity_name = entity_with_related_counts.entity_type
        fieldname = entity_with_related_counts.field_name
        field_metadata = entity_with_related_counts.field_metadata
    
        genericentity = EntityBase(
            entity_name=entity_name
        )
        genericentity.authorization_token = self.authorization_token
        genericentity.base_url = self.env_config.get_path("MEGS", "url")
    
        self.search_api.entity_name = entity_name
        #self.search_api = SearchAPI(self.env_config,entity_name)
        #self.search_api.set_authorization_token(self.authorization_token)
    
        custom_query = self.add_custom_query(field_metadata["DisplayName"])
        (entity_id, target_entity_id) = self.es_client.get_entity_with_related_entities(
            firstclass=entity_name,
            secondclass=field_metadata["TargetEntityName"],
            custom_query=custom_query
        )
        self.logger.info("Found test data in Elastic Search. Test entity -{0} = {1}-, target entity -{2} = {3}-".format(
             entity_name,
             entity_id,
             field_metadata["TargetEntityName"],
             target_entity_id
        ))
    
        #Get entity details and check count
        get_req_code, get_req_text = genericentity.get_entity(
            params={
                "id": entity_id,
                "request_params": "relationCalculationTimeout=-1"
            }
        )
        target_entity_count = json.loads(get_req_text)[fieldname]
        self.logger.info("Target entity count in main entity details: {0}={1}".format(
            fieldname,
            target_entity_count
        ))
    
        #Get entity related entities and check count
        action_type = field_metadata["DisplayName"]
        if action_type in ["Annotations", "Attachments"]:
            action_type = "Notes"
        elif action_type in ["OpenActivities", "Histories"]:
            action_type = "Activities"
    
        get_req_code_1, get_req_text_1 = genericentity.get_entity(
            params={
                "id": entity_id,
                "action": action_type
            }
        )
        related_total_count = 0
        if custom_query:
            query_field = list(custom_query["query"]._values)[-1]
            query_values = []
            query_values.append(
                str(custom_query["query"]._values[list(custom_query["query"]._values)[-1]]).lower()
            )
            for item in json.loads(get_req_text_1)["Objects"]:
                if custom_query["occur_type"] in ["must", "should"]:
                    if str(item[query_field]).lower() in query_values:
                        related_total_count += 1
                else:
                    if str(item[query_field]).lower() not in query_values:
                        related_total_count += 1
        else:
            related_total_count = json.loads(get_req_text_1)["MetaData"]["Total"]
    
        self.logger.info("Get related entity counts completed.  MetaData.Total={0}".format(
            related_total_count
        ))
    
>       assert target_entity_count == related_total_count, "Get related entity counts not match to aggregate count in entity details"
E       AssertionError: Get related entity counts not match to aggregate count in entity details

C:\EdgeDeployment\FunctionalTests\src\Elasticsearch\Tests\InitialPopulation\RelatedEntityCounts\test_aggregate_counts.py:267: AssertionError
-------------------------------- Captured log ---------------------------------
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/authentication
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'29a288488af74399a18e23236dad099b', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/authentication HTTP/1.1" 200 2124
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:00.586000
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/annotation HTTP/1.1" 200 3030
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 1038
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 1950
test_aggregate_counts.py   217 INFO     Found test data in Elastic Search. Test entity -account = 67c8b991-f058-e311-9314-00155d280475-, target entity -annotation = c4b0ddc9-8471-e311-bb29-00155d280475-
EntityBase.py              132 INFO     Sending GET request..
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/account/67c8b991-f058-e311-9314-00155d280475/
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'29a288488af74399a18e23236dad099b', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
requests_api.py            127 DEBUG    Request params: relationCalculationTimeout=-1
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/account/67c8b991-f058-e311-9314-00155d280475/?relationCalculationTimeout=-1 HTTP/1.1" 200 2798
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:04.152000
test_aggregate_counts.py   230 INFO     Target entity count in main entity details: related_note=0
EntityBase.py              132 INFO     Sending GET request..
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/account/67c8b991-f058-e311-9314-00155d280475/Notes
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'29a288488af74399a18e23236dad099b', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/account/67c8b991-f058-e311-9314-00155d280475/Notes HTTP/1.1" 200 1102
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:01.545000
test_aggregate_counts.py   264 INFO     Get related entity counts completed.  MetaData.Total=1
#########################Server error trace#########################
{"index":[],"megs":[{"TimeStamp":"2014-02-18T08:55:31.6241099Z","Message":"Could not get the value of required parameter 'crm_account_website'","ErrorLevel":"WARN","Longdate":"2014-02-18 02:55:30.2814","ThreadId":"119","Logger":"AscendixRE.InsideView.Implementation.Requests.InsideViewRequestUtils","Exception":""},{"TimeStamp":"2014-02-18T08:55:31.8135509Z","Message":"Could not get the value of required parameter 'crm_account_id'","ErrorLevel":"WARN","Longdate":"2014-02-18 02:55:31.4043","ThreadId":"113","Logger":"AscendixRE.InsideView.Implementation.Requests.InsideViewRequestUtils","Exception":""},{"TimeStamp":"2014-02-18T08:55:32.7451319Z","Message":"Could not get the value of required parameter 'crm_account_website'","ErrorLevel":"WARN","Longdate":"2014-02-18 02:55:32.6601","ThreadId":"55 ","Logger":"AscendixRE.InsideView.Implementation.Requests.InsideViewRequestUtils","Exception":""}]}
