#########################Automated tests trace#########################

self = <Tests.InitialPopulation.EntityCounts.test_es_initial_population.TestElasticSearchInitialPopulation object at 0x03403E70>
entity_type = 'activityparty'
search_api = <Search.Implementation.Contract.search.SearchAPI object at 0x03403A70>

    @pytest.mark.xre_demo
    def test_entity_count(self, entity_type, search_api):
        self.monitoring.base_url = search_api.base_url
        self.monitoring.authorization_token = search_api.authorization_token
>       self.check_entity_count_in_mbl_system(entity_type, "Index", search_api)

C:\EdgeDeployment\FunctionalTests\src\Elasticsearch\Tests\InitialPopulation\EntityCounts\test_es_initial_population.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Tests.InitialPopulation.EntityCounts.test_es_initial_population.TestElasticSearchInitialPopulation object at 0x03403E70>
entity_type = 'activityparty', source = 'Index'
search_api = <Search.Implementation.Contract.search.SearchAPI object at 0x03403A70>

    def check_entity_count_in_mbl_system(self, entity_type=None, source="Index", search_api=None):
        self.logger.info("Start verification count of records in index for {0}".format(entity_type))
        try:
            crm_count = self.receive_number_of_records_in_SQL(entity_type=entity_type)
            es_count = self.es_client.get_entity_count(entity_type)
            search_count = None
            try:
                if search_api:
                    search_api.entity_name = entity_type
                    search_status_code, search_response = search_api.send_search_request(
                        request_body=SearchRequest(
                            Size=1,
                            TermFacetSize=1
                        ).to_json()
                    )
                    search_api.validate_http_response(search_status_code, search_response)
                    search_response = SearchResponse(json.loads(search_response))
                    search_count = search_response.total
            except Exception, e:
                self.logger.exception(e)
    
            if es_count == 0:
                raise RuntimeError("{0} not found in index".format(entity_type))
            self.logger.info("{0} entities found in CRM: {1}".format(entity_type, crm_count))
            self.logger.info("{0} entities found in Index: {1}".format(entity_type, es_count))
            self.logger.info("{0} entities found in SearchResult: {1}".format(entity_type, search_count))
            if crm_count == es_count:
                self.logger.info(
                    "Number of records in {0} match to MSSQL DB - PASSED".format(source)
                )
            else:
                assert False, "Number of records in {0} match to MSSQL DB - FAILED: {1} -> {2}".format(
                    source,
                    es_count,
                    crm_count)
    
            if search_count:
                if crm_count == search_count:
                    self.logger.info(
                        "Number of records in SearchResult Total(*) match to MSSQL DB - PASSED".format(source)
                    )
                else:
                    assert False, \
                        "Number of records in SearchResult Total(*) not match to MSSQL DB - FAILED: {0} -> {1}".format(
                            search_count,
                            crm_count
                        )
    
        except Exception, e:
            self.logger.exception(e)
>           raise Exception, e.message
E           Exception: Number of records in Index match to MSSQL DB - FAILED: 1495 -> 1474

C:\EdgeDeployment\FunctionalTests\src\Elasticsearch\Tests\InitialPopulation\EntityCounts\test_es_initial_population.py:96: Exception
-------------------------------- Captured log ---------------------------------
test_es_initial_population.py   29 INFO     
Starting test: test_entity_count
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/authentication
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'e1a18037a60f4528be3edb07f07f316d', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/authentication HTTP/1.1" 200 2124
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:01.014000
test_es_initial_population.py   47 INFO     Start verification count of records in index for activityparty
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/Monitoring/activityparty/counts
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'e1a18037a60f4528be3edb07f07f316d', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/Monitoring/activityparty/counts HTTP/1.1" 200 22
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:00.291000
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/activityparty HTTP/1.1" 200 4569
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/activityparty_1/_count HTTP/1.1" 200 62
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: POST
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/search/activityparty
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'e1a18037a60f4528be3edb07f07f316d', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
requests_api.py            104 DEBUG    Request body: {"ResultsFormat": null, "From": 0, "SelectedDateTimeFacets": null, "Relations": [], "PinTo": {"lat": -27.47018, "lon": 153.02911}, "NumericFacetFilters": [], "OrderBy": [{"Field": "_score", "IsDescending": "true"}], "GeoPolygonFilters": [], "TermFacetFilters": [], "FieldFilters": [], "GeoDistanceFacetFilters": [], "ScriptFilters": [], "Ids": [], "SelectedNumericFacets": null, "RelationCounts": [], "Options": null, "SelectedTermFacets": null, "DateTimeFacetFilters": [], "TermFacetSize": 1, "SelectedGeoFacets": null, "Query": "*", "Size": 1}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "POST /xre2113qa.nightly/api/search/activityparty HTTP/1.1" 200 2909
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:00.629000
test_es_initial_population.py   69 INFO     activityparty entities found in CRM: 1474
test_es_initial_population.py   70 INFO     activityparty entities found in Index: 1495
test_es_initial_population.py   71 INFO     activityparty entities found in SearchResult: 1495
test_es_initial_population.py   95 ERROR    Number of records in Index match to MSSQL DB - FAILED: 1495 -> 1474
Traceback (most recent call last):
  File "C:\EdgeDeployment\FunctionalTests\src\Elasticsearch\Tests\InitialPopulation\EntityCounts\test_es_initial_population.py", line 80, in check_entity_count_in_mbl_system
    crm_count)
AssertionError: Number of records in Index match to MSSQL DB - FAILED: 1495 -> 1474
test_es_initial_population.py   98 INFO     Stop verification count of records in Index for activityparty
#########################Server error trace#########################
{"index":[],"megs":[]}
