#########################Automated tests trace#########################

self = <Search.Tests.SearchWithRelations.test_search_with_relations.TestSearchWithRelations object at 0x044E8B10>
entity_with_test_field = <PyTest.InputTestCriteria.InputTestCriteria.EntityWithField object at 0x0348A8D0>
search_api = <Search.Implementation.Contract.search.SearchAPI object at 0x044E88D0>

    @pytest.mark.xre_demo
    def test_search_with_relations_simple(self, entity_with_test_field, search_api):
        if isinstance(entity_with_test_field, EntityWithField):
            entity_type = entity_with_test_field.entity_type
            related_entities = entity_with_test_field.field_name.split(",")
    
            search_api.entity_name = entity_type
    
            self.logger.debug(entity_with_test_field.to_str_repr())
    
            try:
                ids, related_ids = self.get_entity_ids_related_to(
                    entity_type,
                    related_entities,
                    self.es_client
                )
                related_ids = dict(zip(ids, related_entities))
                response_code, response_text = search_api.send_search_request(
                    request_body=SearchRequest(
                        ResultsFormat="Hit",
                        Relations=related_entities,
                        RelationCounts=related_entities,
                        Ids=ids
                    ).to_json()
                )
                self.assertSearchResponse(response_code, response_text, validate_result=True)
    
                search_response = SearchResponse(json.loads(response_text))
    
                self.assertSearchWithRelations(
                    search_response,
                    related_ids
                )
            except AssertionError, e:
                self.logger.exception(e)
                pytest.fail("Search with relations not working for {0}. Inner assertion: {1}".format(
                    str(entity_with_test_field),
>                   e.message
                ))
E               Failed: Search with relations not working for account__list,connection,contact,awx_propertysale,opportunity,annotation. Inner assertion: Search result not contain Relations, RelationCounts fields

C:\EdgeDeployment\FunctionalTests\src\Search\Tests\SearchWithRelations\test_search_with_relations.py:65: Failed
-------------------------------- Captured log ---------------------------------
test_search_with_relations.py   26 INFO     
Starting test: test_search_with_relations_simple
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/authentication
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'f3fe99178c8a4ab5b967f14bbb68196a', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/authentication HTTP/1.1" 200 2097
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:01.580000
test_search_with_relations.py   36 DEBUG    
---Input data---
test_entity_type=account
field_name=list,connection,contact,awx_propertysale,opportunity,annotation
term_facet_size=None
field_metadata=None
---------------
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/listmember HTTP/1.1" 200 2345
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 123
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/listmember HTTP/1.1" 200 2345
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 823
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 1933
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/connection HTTP/1.1" 200 5244
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 123
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/connection HTTP/1.1" 200 5244
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 1699
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 4636
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/contact HTTP/1.1" 200 15916
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 124
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/contact HTTP/1.1" 200 15916
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 2457
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 2172
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/awx_propertysale HTTP/1.1" 200 9854
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 124
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/awx_propertysale HTTP/1.1" 200 9854
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 1972
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 5149
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/opportunity HTTP/1.1" 200 20477
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 6549
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 2057
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/annotation HTTP/1.1" 200 3030
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 1000
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 5608
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: POST
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/search/account
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'f3fe99178c8a4ab5b967f14bbb68196a', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
requests_api.py            104 DEBUG    Request body: {"ResultsFormat": "Hit", "From": 0, "SelectedDateTimeFacets": null, "Relations": ["list", "connection", "contact", "awx_propertysale", "opportunity", "annotation"], "PinTo": {"lat": -27.47018, "lon": 153.02911}, "NumericFacetFilters": [], "OrderBy": [{"Field": "_score", "IsDescending": "true"}], "GeoPolygonFilters": [], "TermFacetFilters": [], "FieldFilters": [], "GeoDistanceFacetFilters": [], "ScriptFilters": [], "Ids": ["697c3606-b756-e311-9314-00155d280475", "6b7c3606-b756-e311-9314-00155d280475", "637c3606-b756-e311-9314-00155d280475", "617c3606-b756-e311-9314-00155d280475", "84b0c5b3-fd6b-e311-bb29-00155d280475", "46a7648a-ac6e-e311-bb29-00155d280475"], "SelectedNumericFacets": null, "RelationCounts": ["list", "connection", "contact", "awx_propertysale", "opportunity", "annotation"], "Options": null, "SelectedTermFacets": null, "DateTimeFacetFilters": [], "TermFacetSize": 25, "SelectedGeoFacets": null, "Query": "*", "Size": 25}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "POST /xre2113qa.nightly/api/search/account HTTP/1.1" 200 245462
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:13.520000
test_search_with_relations.py   62 ERROR    Search result not contain Relations, RelationCounts fields
Traceback (most recent call last):
  File "C:\EdgeDeployment\FunctionalTests\src\Search\Tests\SearchWithRelations\test_search_with_relations.py", line 59, in test_search_with_relations_simple
    related_ids
  File "C:\EdgeDeployment\FunctionalTests\src\Search\Implementation\Assertions\SearchWithRelationsAssertMixin.py", line 9, in assertSearchWithRelations
    set(result.source.keys())), "Search result not contain Relations, RelationCounts fields"
AssertionError: Search result not contain Relations, RelationCounts fields
#########################Server error trace#########################
{"index":[],"megs":[]}
